leftnav:
- identifier: 494803a6-d092-5658-1b5c-b898b220d5da
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 162f8cc3-ab62-9ebf-bf11-9334b6618eaf
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: d05ead04-435c-0410-a0f6-335b812199c6
  name: Assignments
  url: /pages/assignments
  weight: 30
- identifier: 8089d5b4-6faa-2eee-0048-df1d37de02d0
  name: Related Resources
  url: /pages/related-resources
  weight: 40
